# Evolution API — pinned to v2.3.7 by tag AND digest.
# DO NOT upgrade past v2.3.x: v2.4.0+ requires Evolution Foundation license
# activation. Version bumps happen only via reviewed PRs from the weekly
# upstream-check workflow, which enforces the 2.3.x ceiling.
FROM evoapicloud/evolution-api:v2.3.7@sha256:1bd8afc4a6cf48822e6cf02469aeae7bd35a12a6b616eacd1291926307f4d339
